apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scheduler-ratelimit
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha2
    kind: KubeSchedulerConfiguration
    bindTimeoutSeconds: 600
    clientConnection:
      acceptContentTypes: ""
      burst: 100
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: ""
      qps: 50
    disablePreemption: false
    enableContentionProfiling: true
    enableProfiling: true
    extenders: null
    healthzBindAddress: 0.0.0.0:10251
    leaderElection:
      leaderElect: false
      leaseDuration: 15s
      renewDeadline: 10s
      resourceLock: endpointsleases
      resourceName: kube-scheduler
      resourceNamespace: kube-system
      retryPeriod: 2s
    metricsBindAddress: 0.0.0.0:10251
    percentageOfNodesToScore: 0
    podInitialBackoffSeconds: 1
    podMaxBackoffSeconds: 10
    profiles:
      - schedulerName: ratelimit
        plugins:
          permit:
            enabled:
              - name: RateLimit