apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler-ratelimit
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-scheduler-ratelimit
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-scheduler-ratelimit
    spec:
      serviceAccountName: kube-scheduler-ratelimit
      containers:
        - name: scheduler
          image: codedropau/kube-scheduler-ratelimit:latest
          command:
            - /usr/local/bin/kube-scheduler-ratelimit
            - --config=/etc/scheduler/config.yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          volumeMounts:
            - name: config
              mountPath: /etc/scheduler
      hostNetwork: false
      hostPID: false
      volumes:
        - name: config
          configMap:
            name: kube-scheduler-ratelimit